point_PID_controller:
  ros__parameters:
    wheel_radius: 0.0582
    width: 0.183

    max_linear_vel: 0.22
    max_angular_vel: 1.5

    sample_freq: 50

    point_tolerance: 0.01
    angle_tolerance: 0.02

    kp_dist: 1.5
    ki_dist: 0.0
    kd_dist: 0.08

    kp_yaw: 2.5
    ki_yaw: 0.0
    kd_yaw: 0.15

    filter_alpha: 0.3
